@startuml
skinparam linestyle ortho

rectangle "s1:Switch" as s1
rectangle "s2:Switch" as s2
rectangle "s3:Switch" as s3
rectangle "s4:Switch" as s4
rectangle "l1:Light" as l1
rectangle "l2:Light" as l2

rectangle ":Couloir" as c

c --> s1
c --> s2

s3 <- c
c -> s4

c <-- s1
c <-- s2

s3 -> c
c <- s4



l1 <-- c
l2 <-- c

@enduml
